[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 4, y = 4 }

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 12.0

