dofile(vim.fn.expand('~/dotfiles/nvim/lua/plugins.lua'))
dofile(vim.fn.expand('~/dotfiles/nvim/lua/coc.lua'))
dofile(vim.fn.expand('~/dotfiles/nvim/lua/filer.lua'))
dofile(vim.fn.expand('~/dotfiles/nvim/lua/options.lua'))
dofile(vim.fn.expand('~/dotfiles/nvim/lua/syntax.lua'))
dofile(vim.fn.expand('~/dotfiles/nvim/lua/theme.lua'))
