require('plugins')
require('keybinds')
require('lsp')
require('filer')
require('options')
require('syntax')
require('theme')
require('ime')
require('fzf')
require('git-plug')
require('tab')
require('terminal')
require('indent')
require('status-line')
require('linter')
--require('ale')

